<?

/**
 * General abstract Module for Modules
 * 
 * All other Modules have to be a direct subclass of this one
 * 
 * @author Benjamin Birkenhake <benjamin@birkenhake.org>
 * @package Heimweh
 *
 */


class module{

	public function menu ($path, $theme){
		$data["q"] = $path;
		$data["message"] = "Ich war hier";
		$data = $this->get_last_documents($data);
		theme_call_page($theme, "index", $data);
	}
	
	protected function get_last_documents($data){
		$sql = "SELECT * FROM ".DATABASE_PREFIX."documents ORDER BY date DESC LIMIT 10";
		$result = mysql_query($sql);
		while($row = mysql_fetch_assoc($result)){
			$data["documents"][] = $row;
		}
		return $data;
	}
}